# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='blog/images/already.png', upload_to='blog/images/'),
        ),
    ]
