# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_model_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='/test.png', upload_to='images/'),
        ),
    ]
